package admission

import "errors"

var (
	ErrAdmissionTokenNotFound             = errors.New("admission token not found")
	ErrAdmissionTokenConsumed             = errors.New("admission token already consumed")
	ErrAdmissionTokenExpired              = errors.New("admission token expired")
	ErrAdmissionQQMismatch                = errors.New("admission qq mismatch")
	ErrAdmissionInvalidStatus             = errors.New("admission session status invalid")
	ErrAdmissionPolicyNotFound            = errors.New("admission policy not found")
	ErrAdmissionLinkedSessionRequired     = errors.New("admission linked session required")
	ErrAdmissionFreshmanChannelClosed     = errors.New("freshman admission channel closed")
	ErrAdmissionFreshmanPendingExists     = errors.New("freshman application pending already exists")
	ErrAdmissionMaterialInvalidType       = errors.New("admission material content type invalid")
	ErrAdmissionMaterialInvalidData       = errors.New("admission material image data invalid")
	ErrAdmissionMaterialTooLarge          = errors.New("admission material too large")
	ErrAdmissionMaterialStoreUnavailable  = errors.New("admission material store unavailable")
	ErrAdmissionEmailDomainNotAllowed     = errors.New("admission school email domain not allowed")
	ErrAdmissionEmailSenderUnavailable    = errors.New("admission email sender unavailable")
	ErrAdmissionRedisUnavailable          = errors.New("admission redis unavailable")
	ErrAdmissionOTPExpired                = errors.New("admission email otp expired")
	ErrAdmissionOTPInvalid                = errors.New("admission email otp invalid")
	ErrAdmissionOTPMaxAttempts            = errors.New("admission email otp max attempts exceeded")
	ErrAdmissionOTPCooldown               = errors.New("admission email otp cooldown")
	ErrAdmissionSSONotConfigured          = errors.New("admission school sso not configured")
	ErrAdmissionSSOStateInvalid           = errors.New("admission school sso state invalid")
	ErrAdmissionSSOExchangeFailed         = errors.New("admission school sso exchange failed")
	ErrAdmissionSSOIdentityInvalid        = errors.New("admission school sso identity invalid")
	ErrAdmissionSSOProviderUnavailable    = errors.New("admission school sso provider unavailable")
	ErrAdmissionReturnURLNotAllowed       = errors.New("admission return url not allowed")
	ErrAdmissionOperatorUnbound           = errors.New("admission operator qq unbound")
	ErrAdmissionOperatorForbidden         = errors.New("admission operator forbidden")
	ErrAdmissionOperatorAccessUnavailable = errors.New("admission operator access unavailable")
	ErrAdmissionProjectionUnavailable     = errors.New("admission projection unavailable")
	ErrAdmissionManagementGuildForbidden  = errors.New("admission management guild forbidden")
	ErrAdmissionReviewExtensionTooLong    = errors.New("admission review extension too long")
	ErrAdmissionApplicationNotFound       = errors.New("admission application not found")
	ErrMemberBlacklisted                  = errors.New("member is blacklisted")
	ErrAdmissionBlacklistNotFound         = errors.New("admission blacklist not found")
	ErrMemberBlacklistInvalidInput        = errors.New("member blacklist invalid input")
	ErrMemberBlacklistSourceForbidden     = errors.New("member blacklist source forbidden")
	ErrMemberBlacklistNotFound            = errors.New("member blacklist not found")
)
