package admission

import "errors"

var (
	ErrAdmissionTokenNotFound              = errors.New("admission token not found")
	ErrAdmissionTokenConsumed              = errors.New("admission token already consumed")
	ErrAdmissionTokenExpired               = errors.New("admission token expired")
	ErrAdmissionQQMismatch                 = errors.New("admission qq mismatch")
	ErrAdmissionInvalidInput               = errors.New("admission input invalid")
	ErrAdmissionInvalidStatus              = errors.New("admission session status invalid")
	ErrAdmissionSessionNotFound            = errors.New("admission session not found")
	ErrAdmissionPolicyNotFound             = errors.New("admission policy not found")
	ErrAdmissionPolicyAlreadyExists        = errors.New("admission policy already exists")
	ErrAdmissionLinkedSessionRequired      = errors.New("admission linked session required")
	ErrAdmissionFreshmanChannelClosed      = errors.New("freshman admission channel closed")
	ErrAdmissionFreshmanPendingExists      = errors.New("freshman application pending already exists")
	ErrAdmissionMaterialInvalidType        = errors.New("admission material content type invalid")
	ErrAdmissionMaterialInvalidData        = errors.New("admission material image data invalid")
	ErrAdmissionMaterialTooLarge           = errors.New("admission material too large")
	ErrAdmissionMaterialStoreUnavailable   = errors.New("admission material store unavailable")
	ErrAdmissionCameraHandoffNotFound      = errors.New("admission camera handoff not found")
	ErrAdmissionCameraHandoffExpired       = errors.New("admission camera handoff expired")
	ErrAdmissionCameraHandoffLocked        = errors.New("admission camera handoff locked")
	ErrAdmissionCameraHandoffInvalidChoice = errors.New("admission camera handoff continuation invalid")
	ErrAdmissionEmailDomainNotAllowed      = errors.New("admission school email domain not allowed")
	ErrAdmissionEmailSenderUnavailable     = errors.New("admission email sender unavailable")
	ErrAdmissionAcademicLookupUnavailable  = errors.New("admission academic lookup unavailable")
	ErrAdmissionStudentIDRequired          = errors.New("admission student id required")
	ErrAdmissionStudentIDInvalid           = errors.New("admission student id invalid")
	ErrAdmissionStudentNameRequired        = errors.New("admission student name required")
	ErrAdmissionStudentNameInvalid         = errors.New("admission student name invalid")
	ErrAdmissionStudentRecordNotFound      = errors.New("admission student record not found")
	ErrAdmissionStudentNameMismatch        = errors.New("admission student name mismatch")
	ErrAdmissionRedisUnavailable           = errors.New("admission redis unavailable")
	ErrAdmissionOTPExpired                 = errors.New("admission email otp expired")
	ErrAdmissionOTPInvalid                 = errors.New("admission email otp invalid")
	ErrAdmissionOTPMaxAttempts             = errors.New("admission email otp max attempts exceeded")
	ErrAdmissionOTPCooldown                = errors.New("admission email otp cooldown")
	ErrAdmissionSSONotConfigured           = errors.New("admission school sso not configured")
	ErrAdmissionSSOStateInvalid            = errors.New("admission school sso state invalid")
	ErrAdmissionSSOExchangeFailed          = errors.New("admission school sso exchange failed")
	ErrAdmissionSSOIdentityInvalid         = errors.New("admission school sso identity invalid")
	ErrAdmissionSSOProviderUnavailable     = errors.New("admission school sso provider unavailable")
	ErrAdmissionReturnURLNotAllowed        = errors.New("admission return url not allowed")
	ErrAdmissionOperatorUnbound            = errors.New("admission operator qq unbound")
	ErrAdmissionOperatorForbidden          = errors.New("admission operator forbidden")
	ErrAdmissionOperatorAccessUnavailable  = errors.New("admission operator access unavailable")
	ErrAdmissionProjectionUnavailable      = errors.New("admission projection unavailable")
	ErrAdmissionManagementGuildForbidden   = errors.New("admission management guild forbidden")
	ErrAdmissionReviewExtensionTooLong     = errors.New("admission review extension too long")
	ErrAdmissionApplicationNotFound        = errors.New("admission application not found")
	ErrAdmissionSchoolNotFound             = errors.New("admission school not found")
	ErrAdmissionSchoolDisabled             = errors.New("admission school disabled")
	ErrAdmissionPendingActionFilterInvalid = errors.New("admission pending action filter invalid")
	ErrMemberBlacklisted                   = errors.New("member is blacklisted")
	ErrAdmissionBlacklistNotFound          = errors.New("admission blacklist not found")
	ErrMemberBlacklistInvalidInput         = errors.New("member blacklist invalid input")
	ErrMemberBlacklistSourceForbidden      = errors.New("member blacklist source forbidden")
	ErrMemberBlacklistNotFound             = errors.New("member blacklist not found")
)
