package studentverification

import "errors"

var (
	ErrSchoolNotFound                  = errors.New("verification school not found")
	ErrSchoolUnavailable               = errors.New("verification school unavailable")
	ErrMethodUnavailable               = errors.New("verification method unavailable")
	ErrApplicationNotFound             = errors.New("verification application not found")
	ErrApplicationExpired              = errors.New("verification application expired")
	ErrApplicationState                = errors.New("verification application state conflict")
	ErrConsentRequired                 = errors.New("current privacy notice consent required")
	ErrInformationMismatch             = errors.New("verification information mismatch")
	ErrDependencyUnavailable           = errors.New("verification dependency unavailable")
	ErrSubjectConflict                 = errors.New("enrollment subject belongs to another user")
	ErrCredentialNotFound              = errors.New("verification credential not found")
	ErrCredentialState                 = errors.New("verification credential state conflict")
	ErrContinuationInvalid             = errors.New("verification continuation invalid")
	ErrEmailOTPCooldown                = errors.New("student email otp cooldown active")
	ErrEmailOTPExpired                 = errors.New("student email otp expired")
	ErrEmailOTPInvalid                 = errors.New("student email otp invalid")
	ErrEmailOTPMaxAttempts             = errors.New("student email otp maximum attempts reached")
	ErrInboundEmailChallengeNotFound   = errors.New("inbound email challenge not found")
	ErrInboundEmailEventInvalid        = errors.New("inbound email event invalid")
	ErrSchoolAccountRejected           = errors.New("school account verification rejected")
	ErrSchoolAccountLocked             = errors.New("school account is locked or disabled")
	ErrSchoolAccountNotStudent         = errors.New("school account is not an eligible student")
	ErrPhoneInvalid                    = errors.New("invalid mainland China phone number")
	ErrPhoneOperationNotFound          = errors.New("phone operation not found")
	ErrPhoneOperationConflict          = errors.New("phone operation state conflict")
	ErrPhoneOwnershipConflict          = errors.New("phone binding conflict")
	ErrPhoneAlreadyBound               = errors.New("phone is already bound")
	ErrPhoneNotBound                   = errors.New("phone is not bound")
	ErrPhoneOTPCooldown                = errors.New("phone otp cooldown active")
	ErrPhoneOTPExpired                 = errors.New("phone otp expired")
	ErrPhoneOTPInvalid                 = errors.New("phone otp invalid")
	ErrPhoneOTPMaxAttempts             = errors.New("phone otp maximum attempts reached")
	ErrPhoneOTPRateLimited             = errors.New("phone otp rate limited")
	ErrManualReviewNotFound            = errors.New("manual review case not found")
	ErrManualReviewState               = errors.New("manual review state conflict")
	ErrManualReviewInvalidForm         = errors.New("manual review form is invalid")
	ErrManualReviewSelfDecision        = errors.New("reviewer cannot decide own application")
	ErrManualMaterialStoreUnavailable  = errors.New("manual review material store unavailable")
	ErrManualMaterialInvalidType       = errors.New("manual review material type is invalid")
	ErrManualMaterialInvalidData       = errors.New("manual review material data is invalid")
	ErrManualMaterialTooLarge          = errors.New("manual review material is too large")
	ErrManualMaterialPixelBounds       = errors.New("manual review material pixel bounds are invalid")
	ErrManualMaterialLimit             = errors.New("manual review material limit reached")
	ErrManualMaterialRequired          = errors.New("manual review material is required")
	ErrManualMaterialNotFound          = errors.New("manual review material not found")
	ErrManualHandoffNotFound           = errors.New("manual camera handoff not found")
	ErrManualHandoffExpired            = errors.New("manual camera handoff expired")
	ErrManualHandoffState              = errors.New("manual camera handoff state conflict")
	ErrManualHandoffChoice             = errors.New("manual camera handoff continuation is invalid")
	ErrManualEmailVerificationRequired = errors.New("manual review email verification is required")
	ErrManualEmailOTPCooldown          = errors.New("manual review email otp cooldown active")
	ErrManualEmailOTPExpired           = errors.New("manual review email otp expired")
	ErrManualEmailOTPInvalid           = errors.New("manual review email otp invalid")
	ErrManualEmailOTPMaxAttempts       = errors.New("manual review email otp maximum attempts reached")
	ErrAdminConfigInvalid              = errors.New("student verification administration config invalid")
	ErrAdminConfigRevision             = errors.New("student verification administration config revision conflict")
	ErrAdminConfigDependency           = errors.New("student verification administration dependency unavailable")
	ErrAdminConflictNotFound           = errors.New("student subject conflict not found")
	ErrAdminConflictState              = errors.New("student subject conflict state changed")
	ErrAdminRosterSyncConflict         = errors.New("manual roster sync already in flight")
)
