packages:
  - 'web'
  - 'uniappx'
  - 'shared'
overrides:
  '@intlify/core-base@>=9.1.0 <9.14.5': 9.14.5
  '@intlify/message-resolver@>=9.1.0 <9.1.11': 9.1.11
  adm-zip@<0.6.0: 0.6.0
  defu@<6.1.5: 6.1.5
  picomatch@<2.3.2: 2.3.2
  picomatch@>=4.0.0 <4.0.4: 4.0.4
  postcss@<8.5.18: 8.5.18
  vite@>=6.0.0 <6.4.3: 6.4.3
allowBuilds:
  core-js: true
  core-js-pure: true
  esbuild: true
  vue-demi: true
