package openplatform

import "errors"

var (
	ErrAppNotFound                  = errors.New("open platform app not found")
	ErrAppAlreadyExists             = errors.New("open platform app already exists")
	ErrAppNotApproved               = errors.New("open platform app is not approved")
	ErrAppNotActive                 = errors.New("open platform app is not active")
	ErrInvalidAppProfile            = errors.New("open platform app profile is invalid")
	ErrInvalidAppStatus             = errors.New("open platform app status is invalid")
	ErrInvalidAuditFilter           = errors.New("open platform audit filter is invalid")
	ErrInvalidTokenProbeFilter      = errors.New("open platform token probe filter is invalid")
	ErrInvalidResourceAccess        = errors.New("open platform resource access request is invalid")
	ErrInvalidResourceAccessToken   = errors.New("open platform resource access token is invalid")
	ErrResourceAccessReasonRequired = errors.New("open platform resource access reason is required")
	ErrResourceAccessUnavailable    = errors.New("open platform resource authorization unavailable")
	ErrLifecycleReasonRequired      = errors.New("open platform lifecycle reason is required")
	ErrRedirectURIRequestNotFound   = errors.New("open platform redirect URI request not found")
	ErrRedirectURIReasonRequired    = errors.New("open platform redirect URI reason is required")
	ErrInvalidScope                 = errors.New("open platform scope is invalid")
	ErrScopeAlreadyApproved         = errors.New("open platform scope is already approved")
	ErrScopeAlreadyPending          = errors.New("open platform scope is already pending")
	ErrScopeReasonRequired          = errors.New("open platform scope reason is required")
	ErrScopeNotApproved             = errors.New("open platform scope is not approved")
	ErrTokenMinimizationProbe       = errors.New("open platform token minimization probe failed")
	ErrDisclosureRateLimited        = errors.New("open platform disclosure rate limited")
	ErrDisclosureClientMismatch     = errors.New("open platform disclosure client does not match authenticated client")
	ErrConsentRequired              = errors.New("open platform consent is required")
	ErrConsentTokenInvalid          = errors.New("open platform consent token is invalid")
	ErrProfileIncomplete            = errors.New("open platform profile is incomplete")
	ErrCompletionTokenInvalid       = errors.New("open platform profile completion token is invalid")
	ErrRedirectURINotAllowed        = errors.New("open platform redirect URI is not allowed")
	ErrDisclosureUnavailable        = errors.New("open platform disclosure unavailable")
)
