/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Source of truth:
 *   server/internal/pkg/capability/catalog.go
 *
 * Regenerate with:
 *   cd clients && pnpm run generate:capabilities
 */

export const ADMIN_DASHBOARD_VIEW = 'admin:dashboard:view' as const
export const ADMIN_REVIEWS_MANAGE = 'admin:reviews:manage' as const
export const ADMIN_REVIEWS_EDIT_CONTENT = 'admin:reviews:edit_content' as const
export const ADMIN_REPORTS_MANAGE = 'admin:reports:manage' as const
export const ADMIN_TEACHERS_MANAGE = 'admin:teachers:manage' as const
export const ADMIN_SENSITIVE_WORDS_MANAGE = 'admin:sensitive_words:manage' as const
export const ADMIN_LOGS_VIEW = 'admin:logs:view' as const
export const USER_SCHOOL_READ = 'user:school:read' as const
export const USER_SCHOOL_UPDATE = 'user:school:update' as const
export const USER_SYSTEM_READ = 'user:system:read' as const
export const USER_SYSTEM_UPDATE = 'user:system:update' as const
export const IAM_GRANTS_MANAGE = 'iam:grants:manage' as const
export const STUDENT_ROSTER_READ = 'student:roster:read' as const
export const STUDENT_ROSTER_ACTIVATE = 'student:roster:activate' as const
export const STUDENT_ROSTER_DECRYPT_PII = 'student:roster:decrypt_pii' as const
export const STUDENT_MANUAL_REVIEW_READ = 'student:manual_review:read' as const
export const STUDENT_MANUAL_REVIEW_DECIDE = 'student:manual_review:decide' as const
export const STUDENT_MANUAL_MATERIAL_ACCESS = 'student:manual_material:access' as const
export const STUDENT_VERIFICATION_CONFIG_READ = 'student:verification_config:read' as const
export const STUDENT_VERIFICATION_CONFIG_UPDATE = 'student:verification_config:update' as const
export const STUDENT_CREDENTIAL_READ = 'student:credential:read' as const
export const STUDENT_CREDENTIAL_REVOKE = 'student:credential:revoke' as const
export const STUDENT_SUBJECT_CONFLICT_READ = 'student:subject_conflict:read' as const
export const STUDENT_SUBJECT_CONFLICT_RESOLVE = 'student:subject_conflict:resolve' as const
export const CAMPUS_CONNECTOR_HEALTH_READ = 'campus_connector:health:read' as const
export const CAMPUS_CONNECTOR_MANAGE = 'campus_connector:manage' as const
export const ADMISSION_POLICY_READ = 'admission:policy:read' as const
export const ADMISSION_POLICY_UPDATE = 'admission:policy:update' as const
export const ADMISSION_SESSION_READ = 'admission:session:read' as const
export const ADMISSION_SESSION_MANAGE = 'admission:session:manage' as const
export const MEMBER_BLACKLIST_READ = 'member_blacklist:read' as const
export const MEMBER_BLACKLIST_MANAGE = 'member_blacklist:manage' as const
export const OPEN_PLATFORM_READ = 'open_platform:read' as const
export const OPEN_PLATFORM_MANAGE = 'open_platform:manage' as const
export const REVIEW_LIST_FULL = 'review:list:full' as const
export const REVIEW_CREATE = 'review:create' as const
export const REVIEW_EDIT_OWN = 'review:edit:own' as const
export const REVIEW_DELETE_OWN = 'review:delete:own' as const
export const REVIEW_LIST_BRIEF = 'review:list:brief' as const

export const ALL_CAPABILITIES = [
  ADMIN_DASHBOARD_VIEW,
  ADMIN_REVIEWS_MANAGE,
  ADMIN_REVIEWS_EDIT_CONTENT,
  ADMIN_REPORTS_MANAGE,
  ADMIN_TEACHERS_MANAGE,
  ADMIN_SENSITIVE_WORDS_MANAGE,
  ADMIN_LOGS_VIEW,
  USER_SCHOOL_READ,
  USER_SCHOOL_UPDATE,
  USER_SYSTEM_READ,
  USER_SYSTEM_UPDATE,
  IAM_GRANTS_MANAGE,
  STUDENT_ROSTER_READ,
  STUDENT_ROSTER_ACTIVATE,
  STUDENT_ROSTER_DECRYPT_PII,
  STUDENT_MANUAL_REVIEW_READ,
  STUDENT_MANUAL_REVIEW_DECIDE,
  STUDENT_MANUAL_MATERIAL_ACCESS,
  STUDENT_VERIFICATION_CONFIG_READ,
  STUDENT_VERIFICATION_CONFIG_UPDATE,
  STUDENT_CREDENTIAL_READ,
  STUDENT_CREDENTIAL_REVOKE,
  STUDENT_SUBJECT_CONFLICT_READ,
  STUDENT_SUBJECT_CONFLICT_RESOLVE,
  CAMPUS_CONNECTOR_HEALTH_READ,
  CAMPUS_CONNECTOR_MANAGE,
  ADMISSION_POLICY_READ,
  ADMISSION_POLICY_UPDATE,
  ADMISSION_SESSION_READ,
  ADMISSION_SESSION_MANAGE,
  MEMBER_BLACKLIST_READ,
  MEMBER_BLACKLIST_MANAGE,
  OPEN_PLATFORM_READ,
  OPEN_PLATFORM_MANAGE,
  REVIEW_LIST_FULL,
  REVIEW_CREATE,
  REVIEW_EDIT_OWN,
  REVIEW_DELETE_OWN,
  REVIEW_LIST_BRIEF,
] as const

export const ADMIN_ENTRY_CAPABILITIES = [
  ADMIN_DASHBOARD_VIEW,
  ADMIN_REVIEWS_MANAGE,
  ADMIN_REVIEWS_EDIT_CONTENT,
  ADMIN_REPORTS_MANAGE,
  ADMIN_TEACHERS_MANAGE,
  ADMIN_SENSITIVE_WORDS_MANAGE,
  ADMIN_LOGS_VIEW,
  USER_SCHOOL_READ,
  USER_SCHOOL_UPDATE,
  USER_SYSTEM_READ,
  USER_SYSTEM_UPDATE,
  IAM_GRANTS_MANAGE,
  STUDENT_ROSTER_READ,
  STUDENT_ROSTER_ACTIVATE,
  STUDENT_ROSTER_DECRYPT_PII,
  STUDENT_MANUAL_REVIEW_READ,
  STUDENT_MANUAL_REVIEW_DECIDE,
  STUDENT_MANUAL_MATERIAL_ACCESS,
  STUDENT_VERIFICATION_CONFIG_READ,
  STUDENT_VERIFICATION_CONFIG_UPDATE,
  STUDENT_CREDENTIAL_READ,
  STUDENT_CREDENTIAL_REVOKE,
  STUDENT_SUBJECT_CONFLICT_READ,
  STUDENT_SUBJECT_CONFLICT_RESOLVE,
  CAMPUS_CONNECTOR_HEALTH_READ,
  CAMPUS_CONNECTOR_MANAGE,
  ADMISSION_POLICY_READ,
  ADMISSION_POLICY_UPDATE,
  ADMISSION_SESSION_READ,
  ADMISSION_SESSION_MANAGE,
  MEMBER_BLACKLIST_READ,
  MEMBER_BLACKLIST_MANAGE,
  OPEN_PLATFORM_READ,
  OPEN_PLATFORM_MANAGE,
] as const

export const ROLE_NAMES = ["super_admin", "school_admin", "section_admin", "section_moderator", "section_reviewer", "verified_student", "freshman_provisional", "user"] as const

export const ROLE_CAPABILITIES = {
  "super_admin": [ADMIN_DASHBOARD_VIEW, ADMIN_REVIEWS_MANAGE, ADMIN_REVIEWS_EDIT_CONTENT, ADMIN_REPORTS_MANAGE, ADMIN_TEACHERS_MANAGE, ADMIN_SENSITIVE_WORDS_MANAGE, ADMIN_LOGS_VIEW, USER_SCHOOL_READ, USER_SCHOOL_UPDATE, USER_SYSTEM_READ, USER_SYSTEM_UPDATE, IAM_GRANTS_MANAGE, STUDENT_ROSTER_READ, STUDENT_ROSTER_ACTIVATE, STUDENT_ROSTER_DECRYPT_PII, STUDENT_MANUAL_REVIEW_READ, STUDENT_MANUAL_REVIEW_DECIDE, STUDENT_MANUAL_MATERIAL_ACCESS, STUDENT_VERIFICATION_CONFIG_READ, STUDENT_VERIFICATION_CONFIG_UPDATE, STUDENT_CREDENTIAL_READ, STUDENT_CREDENTIAL_REVOKE, STUDENT_SUBJECT_CONFLICT_READ, STUDENT_SUBJECT_CONFLICT_RESOLVE, CAMPUS_CONNECTOR_HEALTH_READ, CAMPUS_CONNECTOR_MANAGE, ADMISSION_POLICY_READ, ADMISSION_POLICY_UPDATE, ADMISSION_SESSION_READ, ADMISSION_SESSION_MANAGE, MEMBER_BLACKLIST_READ, MEMBER_BLACKLIST_MANAGE, OPEN_PLATFORM_READ, OPEN_PLATFORM_MANAGE],
  "school_admin": [ADMIN_REVIEWS_MANAGE, ADMIN_REVIEWS_EDIT_CONTENT, ADMIN_REPORTS_MANAGE, USER_SCHOOL_READ, USER_SCHOOL_UPDATE, STUDENT_ROSTER_READ, STUDENT_ROSTER_ACTIVATE, STUDENT_MANUAL_REVIEW_READ, STUDENT_MANUAL_REVIEW_DECIDE, STUDENT_MANUAL_MATERIAL_ACCESS, STUDENT_VERIFICATION_CONFIG_READ, STUDENT_VERIFICATION_CONFIG_UPDATE, STUDENT_CREDENTIAL_READ, STUDENT_CREDENTIAL_REVOKE, STUDENT_SUBJECT_CONFLICT_READ, STUDENT_SUBJECT_CONFLICT_RESOLVE, CAMPUS_CONNECTOR_HEALTH_READ],
  "section_admin": [ADMIN_REVIEWS_MANAGE, ADMIN_REPORTS_MANAGE],
  "section_moderator": [ADMIN_REVIEWS_MANAGE, ADMIN_REPORTS_MANAGE],
  "section_reviewer": [],
  "verified_student": [REVIEW_LIST_FULL, REVIEW_CREATE, REVIEW_EDIT_OWN, REVIEW_DELETE_OWN],
  "freshman_provisional": [REVIEW_LIST_FULL, REVIEW_CREATE, REVIEW_EDIT_OWN, REVIEW_DELETE_OWN],
  "user": [REVIEW_LIST_BRIEF],
} as const
