export const OPEN_PLATFORM_AUDIT_EVENT_TYPES = [
  'open_platform.app.approved',
  'open_platform.app.approved_app_ensured',
  'open_platform.app.profile_updated',
  'open_platform.app.redirect_uris.approved',
  'open_platform.app.redirect_uris.rejected',
  'open_platform.app.redirect_uris.requested',
  'open_platform.app.redirect_uris.withdrawn',
  'open_platform.app.resumed',
  'open_platform.app.revoked',
  'open_platform.app.secret_rotated',
  'open_platform.app.suspended',
  'open_platform.app.token_probe.failed',
  'open_platform.app.token_probe.passed',
  'open_platform.app.token_probe.runtime.failed',
  'open_platform.app.token_probe.runtime.passed',
  'open_platform.app.withdrawn',
  'open_platform.consent.denied',
  'open_platform.consent.granted',
  'open_platform.consent.revoked',
  'open_platform.disclosure.denied',
  'open_platform.disclosure.granted',
  'open_platform.disclosure.replay_detected',
  'open_platform.resource_access.checked',
  'open_platform.resource_access.granted',
  'open_platform.resource_access.revoked',
  'open_platform.scope.approved',
  'open_platform.scope.rejected',
  'open_platform.scope.requested',
  'open_platform.scope.withdrawn',
] as const

export type OpenPlatformAuditEventType =
  (typeof OPEN_PLATFORM_AUDIT_EVENT_TYPES)[number]
