ARG GO_IMAGE=golang:1.26.5-alpine3.24@sha256:0178a641fbb4858c5f1b48e34bdaabe0350a330a1b1149aabd498d0699ff5fb2
FROM ${GO_IMAGE}

WORKDIR /app

RUN apk add --no-cache git ca-certificates tzdata

RUN go install github.com/air-verse/air@v1.67.3

COPY go.mod go.sum ./
RUN go mod download

# 源码通过 volume 挂载，不需要 COPY

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
