import type {
  StuhelperAdminMessageConfig,
  StuhelperBindingMessageConfig,
  StuhelperGroupGuardMessageConfig,
} from './types/index'

export type MessageTemplateVariables = Record<string, unknown>

export const DEFAULT_BINDING_MESSAGES: StuhelperBindingMessageConfig = Object.freeze({
  directOnly: '请在私聊中发送绑定命令。',
  missingCode: '请输入绑定码，例如：{command} ABCD1234',
  successVerified: '绑定成功，当前账号已完成学生认证，加入受控群时会自动放行。',
  successUnverified: '绑定成功。当前账号还未完成学生认证，请先回到 StuHelper 完成认证。',
  unavailable: '绑定失败，平台暂时不可用。',
  invalidCode: '绑定码无效或已过期，请重新生成后再试。',
  unauthorized: '机器人服务鉴权失败，请联系管理员检查后端配置。',
  conflict: '该 QQ 号或 StuHelper 账号已经绑定过其他对象。',
  notConfigured: '后端机器人接口尚未配置完成，请联系管理员。',
})

export const DEFAULT_ADMIN_MESSAGES: StuhelperAdminMessageConfig = Object.freeze({
  guardStatusCommandDescription: '查看当前群待认证成员',
  guardWarningCommandDescription: '查看成员当前警告次数',
  guardReviewListCommandDescription: '查看当前群待复核队列',
  guardBatchMuteCommandDescription: '批量禁言待认证成员',
  guardKickReviewCommandDescription: '提交踢人复核申请',
  guardBlockReviewCommandDescription: '提交踢人并拉黑复核申请',
  freshmanViewCommandDescription: '查看新生认证申请',
  freshmanApproveCommandDescription: '通过新生认证申请',
  freshmanRejectCommandDescription: '驳回新生认证申请',
  freshmanBlacklistReleaseCommandDescription: '解除新生入群认证黑名单',
  commandAccessDenied: '命令权限不足。',
  adminCommandsDisabled: '管理员命令已由 StuHelper WebUI 关闭。',
  guardWarningMissingContext: '请在群聊中执行，或显式传入群号和成员 ID。',
  guardBatchMuteGroupOnly: '请在目标群聊中执行批量禁言。',
  guardBatchMuteInvalidPayload: '请提供禁言秒数和成员 ID 列表，例如：群审批量禁言 120 10001,10002',
  guardBatchMuteNoTargets: '没有找到可操作的待认证成员。',
  guardBatchMuteSuccess: '已批量禁言 {count} 名成员。',
  guardBatchMuteEventSummary: '管理员批量禁言了 {memberId}',
  guardBatchMuteEventReason: '管理员批量禁言',
  guardReviewRequestMissingArgs: '请在群聊中提供成员 ID 和原因。',
  guardReviewRequestSuccess: '已提交{actionLabel}复核申请：{memberId}，原因：{reason}',
  guardReviewRequestEventSummary: '{operatorMemberId} 提交了{actionLabel}复核申请',
  guardReviewKickActionLabel: '踢人',
  guardReviewKickAndBlockActionLabel: '踢人并拉黑',
  guardPendingMembersEmpty: '当前没有待认证成员。',
  guardPendingMembersHeader: '待认证成员：',
  guardPendingMemberLine: '{memberId} 截止 {deadlineAt}',
  guardWarningCounterEmpty: '{memberId} 当前没有警告记录。',
  guardWarningCounterNoReason: '无',
  guardWarningCounterSummary: '{memberId} 当前累计警告 {total} 次，最近原因：{lastReason}',
  guardPendingReviewsEmpty: '当前没有待复核事项。',
  guardPendingReviewsHeader: '待复核队列：',
  guardPendingReviewLine: '{memberId} [{actionType}] {reason}',
  freshmanManagementGroupOnly: '请在新生审核管理群中执行此命令。',
  freshmanMissingApplicationID: '请提供申请 ID。',
  freshmanApproveInvalidFormat: '通过命令格式为：新生审核通过 <申请ID> [+30d]。',
  freshmanApproveInvalidExtension: '审批延长天数格式应为 +30d，且必须是正整数天数。',
  freshmanRejectInvalidFormat: '驳回命令格式为：新生审核驳回 <申请ID> <原因>。',
  freshmanBlacklistReleaseInvalidFormat: '解除命令格式为：新生黑名单解除 <QQ号> <群号|global>。',
  freshmanApproveSuccess: '已通过新生认证申请 {applicationID}。',
  freshmanApproveSuccessWithExtension: '已通过新生认证申请 {applicationID}，临时身份 {expiresInDays} 天后过期。',
  freshmanRejectSuccess: '已驳回新生认证申请 {applicationID}。',
  freshmanBlacklistScopeGlobal: '全局',
  freshmanBlacklistScopeGuild: '群 {guildID} 的',
  freshmanBlacklistReleaseSuccess: '已解除 {qqID} 的{scope}入群认证黑名单。',
  freshmanApplicationSummary: [
    '申请 {applicationID}',
    '状态：{status}',
    '姓名：{applicantName}',
    '学校ID：{schoolID}',
    '专业：{departmentOrMajor}',
    '临时身份过期：{provisionalExpiresAt}',
  ].join('\n'),
  freshmanApplicationDepartmentFallback: '未提供',
  freshmanApplicationExpiryFallback: '未设置',
  freshmanCommandFailed: '新生审核命令执行失败：{error}',
  freshmanOperatorQQUnbound: '你的 QQ 未绑定 StuHelper 管理员账号，请先完成管理员 QQ 绑定。',
  freshmanOperatorForbidden: '你的 StuHelper 账号没有新生审核权限。',
  freshmanManagementGuildForbidden: '当前群不在新生审核管理群白名单内。',
  freshmanBackendForbidden: '后端拒绝执行该审核命令：{message}',
})

export const DEFAULT_GROUP_GUARD_MESSAGES: StuhelperGroupGuardMessageConfig = Object.freeze({
  publicReportCommandDescription: '举报群成员并触发审核',
  diceCommandDescription: '投掷骰子',
  muteLotteryCommandDescription: '随机抽取自己的禁言时长，带保底机制',
  admissionQueryCommandDescription: '查询指定 QQ 的入群认证状态',
  admissionResendCommandDescription: '重发当前仍可继续的入群认证链接',
  admissionRegenerateCommandDescription: '取消旧会话并重新生成入群认证链接',
  admissionSkipCommandDescription: '仅跳过当前群的入群认证，不通过 StuHelper 学生认证',
  admissionResetFailureCountCommandDescription: '清空当前群成员的入群认证失败次数',
  admissionReleaseBlacklistCommandDescription: '解除当前群成员的入群拉黑状态',
  admissionReminder: [
    '{at} ({memberId})请在 {minutes} 分钟内完成 StuHelper 学生身份认证：',
    '{authURL}',
    '{timeoutLine}',
  ].join('\n'),
  admissionTimeoutNormal: '通过后自动解除禁言，超时将移出群聊，可重新加群认证次数：{remainingRetryCount}。',
  admissionTimeoutWithFailures: [
    '通过后自动解除禁言，超时将移出群聊',
    '您已累计{failureCount}次未认证，可重新加群认证次数：{remainingRetryCount}',
  ].join('\n'),
  admissionTimeoutBlacklist: [
    '通过后自动解除禁言，超时将移出群聊',
    '您已累计{failureCount}次未认证，本次超时未认证将永久拉黑',
  ].join('\n'),
  backendPendingReminder: [
    '{at} {reminderTemplate}',
    '认证链接暂时无法创建，机器人会自动重试。',
  ].join('\n'),
  admissionReleaseCompleted: '',
  admissionKickTimeout: '{at} 认证超时，机器人将自动移出群聊。',
  admissionBlacklistKick: '{at} 认证失败次数已达上限，已加入入群黑名单，机器人将移出群聊。',
  antiRecallNotify: '{at} 检测到撤回消息：{content}',
  moderationMuteNotice: '{at} 因 {reason} 被禁言 {seconds} 秒。',
  moderationUnmuteNotice: '{at} 已解除禁言。原因：{reason}',
  moderationKickNotice: '{at} 因 {reason} 将被移出群聊。',
  freshmanForwardSummary: [
    '新生材料审核 {applicationId}',
    '姓名：{applicantName}',
    '学校：{schoolName}',
    '专业：{departmentOrMajor}',
    'QQ：{qqID}',
    '材料：{materialType}',
    '临时身份过期：{provisionalExpiresAt}',
    '通过：新生审核通过 {applicationId}',
    '驳回：新生审核驳回 {applicationId} <原因>',
  ].join('\n'),
  freshmanForwardUnknownField: '未提供',
  freshmanMaterialTypeAdmissionNotice: '录取通知书',
  freshmanMaterialTypeAdmissionCertificate: '录取证明',
  publicReportMissingArgs: '请提供被举报成员 ID 和举报原因。',
  publicCommandsDisabled: '公开命令已由 StuHelper WebUI 关闭。',
  muteLotteryGroupOnly: '抽禁言只能在群聊中使用。',
  commandAccessDenied: '命令权限不足。',
  diceResult: '{memberId} 投出了 d{sides} = {result}',
  muteLotteryResult: '{memberId} 本次自助禁言 {seconds} 秒。',
  muteLotteryPityResult: '保底触发，{memberId} 本次自助禁言 {seconds} 秒。',
  reportGroupOnly: '举报命令只能在群聊中使用。',
  reportRecordedAIUnavailable: '举报已记录。当前未启用 AI 审核，事件已进入人工处理范围。',
  reportAIReviewFailed: '举报已记录，但 AI 审核失败，事件已保留供人工处理。',
  reportHighRisk: '举报已提交，AI 判定为高风险，已进入踢人/拉黑人工复核队列。',
  reportMediumRisk: '举报已提交，AI 判定为中风险，已自动警告并禁言。',
  reportLowRisk: '举报已提交，AI 判定为低风险，已自动记警告。',
  reportNoAction: '举报已提交，AI 未判定出可执行违规动作。',
  admissionCommandGroupOnly: '入群认证命令只能在群聊中使用。',
  admissionCommandsDisabled: '入群认证管理员命令已由 StuHelper WebUI 关闭。',
  admissionCommandMissingQQ: '请提供要操作的 QQ 号。',
  admissionCommandMissingOperator: '无法识别命令执行者 QQ。',
  admissionCommandUnsupportedPlatform: '当前机器人平台不支持入群认证。',
  admissionCommandPolicyDisabled: '当前群未启用 StuHelper 入群认证。',
  admissionCommandNotFound: '未找到该 QQ 的入群认证记录。',
  admissionCommandInvalidState: '当前入群认证状态不允许该操作。',
  admissionCommandUnauthorized: '机器人服务凭据无权访问入群认证接口。',
  admissionCommandFailed: '入群认证命令执行失败。{error}',
  admissionCommandPlatformError: 'StuHelper 平台接口异常：{status} {message}',
  admissionCommandMissingResendURL: '后端没有返回可重发的认证链接。',
  admissionCommandStaleRecord: '入群认证记录已被其他任务处理，请重新查询当前状态。',
  admissionReminderDeliveryDisabled: '入群认证提醒投递方式已全部关闭。',
  admissionReminderDeliveryFailure: '入群认证提醒发送失败：{errors}',
  admissionReminderDeliveryGroupChannelLabel: '群内提醒',
  admissionReminderDeliveryDirectChannelLabel: '私聊/临时会话提醒',
  admissionSkipSuccess: [
    '{at} ({qqID}) 已跳过本群入群认证并解除禁言。',
    '此操作只在本群生效，不代表 StuHelper 学生认证已通过。',
  ].join('\n'),
  admissionAlreadyVerifiedRegenerate: '{at} ({qqID}) 已完成 StuHelper 学生身份认证，已解除禁言，无需重新生成认证链接。',
  admissionResetFailureCountSuccess: '已清空 QQ {qqID} 在本群的入群未认证次数（原次数：{previousFailureCount}）。',
  admissionReleaseBlacklistNotFound: 'QQ {qqID} 在本群没有活动入群拉黑记录。',
  admissionReleaseBlacklistSuccess: '已解除 QQ {qqID} 在本群的入群拉黑状态；未认证次数未清空，如需重新计数请使用“清空入群未认证次数 {qqID}”。',
  admissionQuerySummary: [
    '入群认证状态：{qqID}',
    '状态：{statusLabel}',
    '会话：{sessionID}',
    'QQ 绑定：{qqLinkedLabel}',
    '学生认证：{studentVerificationLabel}',
    '{deadlineLine}',
    '下一步：{nextStep}',
    '{lastBotErrorLine}',
  ].join('\n'),
  admissionQueryDeadlineLink: '链接有效期：{deadlineAt}',
  admissionQueryDeadlineSubmission: '学生认证截止：{deadlineAt}',
  admissionQueryDeadlineManualReview: '人工审核截止：{deadlineAt}',
  admissionQueryDeadlineUnset: '未设置',
  admissionQueryLastBotError: '最近机器人错误：{lastBotError}',
  admissionQueryQQLinked: '已完成',
  admissionQueryQQUnlinked: '未完成',
  admissionQueryStudentVerified: '已通过',
  admissionQueryStudentFreshmanPending: '新生材料待审核',
  admissionQueryStudentUnverified: '未通过',
  admissionStatusJoinedMuted: '等待打开链接并绑定 QQ',
  admissionStatusLinked: '已绑定 QQ，等待学生认证',
  admissionStatusMaterialSubmitted: '新生材料待审核',
  admissionStatusVerified: '学生认证已通过，等待或已完成解除禁言',
  admissionStatusExpiredKicked: '已超时移出或等待移出',
  admissionStatusCancelled: '已取消',
  admissionNextStepJoinedMuted: '让成员打开认证链接登录并完成 QQ 绑定与学生认证；链接找不到时可使用“重发认证链接”。',
  admissionNextStepLinked: 'QQ 已绑定，但还没有学生认证凭据；请继续完成老生邮箱/学校 SSO 认证，或提交新生材料。',
  admissionNextStepMaterialSubmitted: '等待具备审核权限的管理员审核新生材料；审核通过后机器人会解除禁言。',
  admissionNextStepVerifiedWithBotError: '后端已通过学生认证，但机器人执行失败；请检查最近机器人错误和 Koishi 日志。',
  admissionNextStepVerified: '后端已通过学生认证，机器人会解除禁言；若仍被禁言，请查询 Koishi release 日志。',
  admissionNextStepExpiredKickedLinked: '旧会话已超时；该 QQ 曾绑定账号但未完成学生认证，请使用“重新生成认证链接”后重新认证。',
  admissionNextStepExpiredKicked: '旧会话已超时；请使用“重新生成认证链接”后让成员重新认证。',
  admissionNextStepCancelled: '当前会话已取消；请使用“重新生成认证链接”创建新链接。',
  admissionNextStepDefault: '按当前状态继续处理。',
  admissionConsoleSettingsSaved: '已保存入群认证运行开关。',
  admissionConsoleRecordNotFound: '入群认证记录不存在或已结束。',
  admissionConsoleStaleRecord: '入群认证记录已被其他任务处理，请刷新页面后确认当前状态。',
  admissionConsoleResendSuccess: '已重发 QQ {qqID} 的入群认证链接。',
  admissionConsoleVerifiedReleaseSuccess: 'QQ {qqID} 已完成学生认证，已解除禁言。',
  admissionConsoleRegenerateSuccess: '已重新生成 QQ {qqID} 的入群认证链接并重置禁言。',
  admissionConsoleSkipSuccess: '已跳过 QQ {qqID} 在本群的入群认证并解除禁言。',
  admissionConsoleResetFailureCountSuccess: '已清空 QQ {qqID} 在本群的入群未认证次数（原次数：{previousFailureCount}）。',
  admissionConsoleReleaseBlacklistSuccess: '已解除 QQ {qqID} 在本群的入群拉黑状态。',
  admissionConsoleMissingResendURL: '后端没有返回可发送的认证链接。',
  admissionConsoleInvalidMuteDeadline: '入群认证禁言期限无效，无法重置禁言。',
  admissionConsoleBotNotFound: '未找到可操作该记录的 Bot：{platform}/{botSelfID}',
  admissionConsoleErrorNotFound: '未找到该 QQ 的入群认证记录或拉黑记录。',
  admissionConsoleErrorInvalidState: '当前入群认证状态不允许该操作。',
  admissionConsoleErrorUnauthorized: '机器人服务凭据无权访问入群认证接口。',
  admissionConsoleErrorPlatform: 'StuHelper 平台接口异常：{status} {message}',
  admissionConsoleErrorFallback: '入群认证操作失败。',
  moderationWarnEventSummary: '已对 {memberId} 记警告：{reason}',
  moderationMuteEventSummary: '已禁言 {memberId}',
  moderationUnmuteEventSummary: '已解除 {memberId} 的禁言',
  moderationKickEventSummary: '已移出 {memberId}',
  moderationAntiRecallEventSummary: '检测到 {memberId} 撤回消息',
  moderationKeywordHitEventSummary: '{memberId} 命中关键词规则 {ruleId}',
  moderationKeywordHitReason: '关键词命中',
  moderationKeywordRuleHitReason: '关键词规则命中',
  moderationRepeatHitEventSummary: '{memberId} 触发复读检测',
  moderationRepeatHitReason: '复读命中',
  moderationRepeatAutoMuteReason: '复读规则触发自动处罚',
  moderationMuteLotteryEventSummary: '{memberId} 触发抽禁言',
  reportCreatedEventSummary: '{reporterMemberId} 举报了 {targetMemberId}',
  reportAIReviewedEventSummary: 'AI 已完成举报审核：{summary}',
  reportAIWarnReason: 'AI 举报审核：{reason}',
  reportAIMuteReason: 'AI 举报审核命中中风险',
  reportAISummaryFallback: '未返回摘要',
  admissionBlacklistEventSummary: '成员 {memberId} 命中入群黑名单，已移出群聊',
  admissionJoinMutedEventSummary: '已对 {memberId} 执行入群待认证禁言',
  admissionJoinAlreadyVerifiedEventSummary: '已识别 {memberId} 为完成学生认证的成员，跳过入群禁言',
  admissionJoinBackendUnavailableEventSummary: '后端 admission session 创建失败，已对 {memberId} 执行本地兜底禁言',
  admissionJoinBackendVerifiedEventSummary: '后端同步识别 {memberId} 已完成学生认证，已解除本地兜底禁言',
  admissionCommandInvalidMuteDeadline: '入群认证禁言期限无效，无法重置禁言。',
})

export function resolveBindingMessages(config?: Partial<StuhelperBindingMessageConfig>) {
  return { ...DEFAULT_BINDING_MESSAGES, ...config }
}

export function resolveAdminMessages(config?: Partial<StuhelperAdminMessageConfig>) {
  return { ...DEFAULT_ADMIN_MESSAGES, ...config }
}

export function resolveGroupGuardMessages(config?: Partial<StuhelperGroupGuardMessageConfig>) {
  return { ...DEFAULT_GROUP_GUARD_MESSAGES, ...config }
}

export function renderMessageTemplate(template: string, variables: MessageTemplateVariables = {}) {
  if (!template.trim()) return ''
  return template.replace(/\{([A-Za-z0-9_]+)\}/g, (match, key: string) => {
    const value = variables[key]
    if (value === null || value === undefined) return ''
    return String(value)
  })
}
