#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

MODE="${1:-dev}"
if [[ "${MODE}" != "dev" && "${MODE}" != "prod" ]]; then
  die "usage: $0 [dev|prod]"
fi
require_cmd docker
require_cmd curl
require_cmd jq
require_cmd python3

load_env
STACK_NAME_VALUE="${STACK_NAME:-${COMPOSE_PROJECT_NAME:-stuhelper}}"
BOOTSTRAP_VOLUME="${BOOTSTRAP_VOLUME:-${STACK_NAME_VALUE}-zitadel-bootstrap}"
DOCKER_NETWORK_NAME="${DOCKER_NETWORK_NAME:-${STACK_NAME_VALUE}-backend}"

wait_for_zitadel_proxy() {
  local url="http://127.0.0.1:${ZITADEL_EXTERNALPORT:-8085}/ui/v2/login/healthy"
  local host="${ZITADEL_DOMAIN:-localhost}"
  local retries=90
  local i

  for ((i = 1; i <= retries; i++)); do
    if curl -fsS --max-time 5 -H "Host: ${host}" "${url}" >/dev/null 2>&1; then
      log "Zitadel proxy is ready: ${url} (Host: ${host})"
      return 0
    fi
    sleep 2
  done

  die "Zitadel proxy did not become ready in time: ${url} (Host: ${host})"
}

wait_for_zitadel_proxy

log "bootstrapping Zitadel project and OIDC application"
ZITADEL_OUTPUT="$(
  cd "${REPO_ROOT}" && \
  ZITADEL_URL="${ZITADEL_ISSUER:-http://localhost:8085}" \
  REDIRECT_URIS="${ZITADEL_SETUP_REDIRECT_URIS:-${ZITADEL_REDIRECT_URI:-http://localhost:8080/api/v1/auth/callback}}" \
  POST_LOGOUT_URIS="${ZITADEL_SETUP_POST_LOGOUT_URIS:-${WEB_PUBLIC_URL:-http://localhost:3000}}" \
  ./infra/zitadel/setup.sh
)"

printf '%s\n' "${ZITADEL_OUTPUT}"

ZITADEL_PROJECT_ID="$(printf '%s\n' "${ZITADEL_OUTPUT}" | awk -F= '/^ZITADEL_PROJECT_ID=/{print $2}' | tail -n1)"
ZITADEL_CLIENT_ID="$(printf '%s\n' "${ZITADEL_OUTPUT}" | awk -F= '/^ZITADEL_CLIENT_ID=/{print $2}' | tail -n1)"
ZITADEL_CLIENT_SECRET="$(printf '%s\n' "${ZITADEL_OUTPUT}" | awk -F= '/^ZITADEL_CLIENT_SECRET=/{print $2}' | tail -n1)"
ZITADEL_MANAGEMENT_PAT_VALUE="$(docker run --rm -v "${BOOTSTRAP_VOLUME}:/bootstrap:ro" alpine:3.22 cat /bootstrap/admin.pat 2>/dev/null || true)"

[[ -n "${ZITADEL_PROJECT_ID}" ]] || die "failed to extract ZITADEL_PROJECT_ID from setup output"
[[ -n "${ZITADEL_CLIENT_ID}" ]] || die "failed to extract ZITADEL_CLIENT_ID from setup output"
[[ -n "${ZITADEL_CLIENT_SECRET}" ]] || die "failed to extract ZITADEL_CLIENT_SECRET from setup output"
[[ -n "${ZITADEL_MANAGEMENT_PAT_VALUE}" ]] || die "failed to extract ZITADEL_MANAGEMENT_PAT from running Zitadel container"

log "bootstrapping OpenFGA store and model"
if command -v go >/dev/null 2>&1; then
  FGA_OUTPUT="$(
    cd "${REPO_ROOT}" && \
    OPENFGA_API_URL="${OPENFGA_API_URL:-http://localhost:8081}" \
    OPENFGA_STORE_ID="${OPENFGA_STORE_ID:-}" \
    go run ./server/cmd/fga-setup
  )"
else
  FGA_OUTPUT="$(
    docker run --rm \
      --network "${DOCKER_NETWORK_NAME}" \
      -v "${REPO_ROOT}:/workspace" \
      -w /workspace/server \
      -e OPENFGA_API_URL="http://openfga:8080" \
      -e OPENFGA_STORE_ID="${OPENFGA_STORE_ID:-}" \
      golang:1.26-bookworm \
      go run ./cmd/fga-setup
  )"
fi

printf '%s\n' "${FGA_OUTPUT}"

OPENFGA_STORE_ID_VALUE="$(printf '%s\n' "${FGA_OUTPUT}" | awk -F= '/^OPENFGA_STORE_ID=/{print $2}' | tail -n1)"
OPENFGA_MODEL_ID_VALUE="$(printf '%s\n' "${FGA_OUTPUT}" | awk -F= '/^OPENFGA_MODEL_ID=/{print $2}' | tail -n1)"

[[ -n "${OPENFGA_STORE_ID_VALUE}" ]] || die "failed to extract OPENFGA_STORE_ID from setup output"
[[ -n "${OPENFGA_MODEL_ID_VALUE}" ]] || die "failed to extract OPENFGA_MODEL_ID from setup output"

cat >"${GENERATED_ENV_FILE}" <<EOF
# Generated by infra/ops/bootstrap-platform.sh (${MODE})
ZITADEL_PROJECT_ID=${ZITADEL_PROJECT_ID}
ZITADEL_CLIENT_ID=${ZITADEL_CLIENT_ID}
ZITADEL_CLIENT_SECRET=${ZITADEL_CLIENT_SECRET}
ZITADEL_MANAGEMENT_PAT=${ZITADEL_MANAGEMENT_PAT_VALUE}
OPENFGA_STORE_ID=${OPENFGA_STORE_ID_VALUE}
OPENFGA_MODEL_ID=${OPENFGA_MODEL_ID_VALUE}
EOF

log "wrote derived runtime configuration to ${GENERATED_ENV_FILE}"
