#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

MODE="${1:-dev}"
if [[ "${MODE}" != "dev" && "${MODE}" != "prod" ]]; then
  die "usage: $0 [dev|prod]"
fi
require_cmd docker
require_cmd curl
require_cmd jq
require_cmd python3

load_env
STACK_NAME_VALUE="${STACK_NAME:-${COMPOSE_PROJECT_NAME:-stuhelper}}"
DOCKER_NETWORK_NAME="${DOCKER_NETWORK_NAME:-${STACK_NAME_VALUE}-backend}"

wait_for_casdoor() {
  local url="${CASDOOR_ISSUER:-http://localhost:8085}/.well-known/openid-configuration"
  local retries=90
  local i

  for ((i = 1; i <= retries; i++)); do
    if curl -fsS --max-time 5 "${url}" >/dev/null 2>&1; then
      log "Casdoor OIDC metadata is ready: ${url}"
      return 0
    fi
    sleep 2
  done

  die "Casdoor OIDC metadata did not become ready in time: ${url}"
}

wait_for_casdoor
[[ -n "${CASDOOR_CLIENT_ID:-}" ]] || die "CASDOOR_CLIENT_ID must be configured before platform bootstrap"
[[ -n "${CASDOOR_CLIENT_SECRET:-}" ]] || die "CASDOOR_CLIENT_SECRET must be configured before platform bootstrap"
log "using configured Casdoor OIDC application ${CASDOOR_CLIENT_ID}"

log "bootstrapping OpenFGA store and model"
if command -v go >/dev/null 2>&1; then
  FGA_OUTPUT="$(
    cd "${REPO_ROOT}/server" && \
    OPENFGA_API_URL="${OPENFGA_API_URL:-http://localhost:8081}" \
    OPENFGA_STORE_ID="${OPENFGA_STORE_ID:-}" \
    FGA_MODEL_PATH="${FGA_MODEL_PATH:-${REPO_ROOT}/infra/openfga/model.fga}" \
    go run ./cmd/fga-setup
  )"
else
  FGA_OUTPUT="$(
    docker run --rm \
      --network "${DOCKER_NETWORK_NAME}" \
      -v "${REPO_ROOT}:/workspace" \
      -w /workspace/server \
      -e OPENFGA_API_URL="http://openfga:8080" \
      -e OPENFGA_STORE_ID="${OPENFGA_STORE_ID:-}" \
      -e FGA_MODEL_PATH="${FGA_MODEL_PATH:-/workspace/infra/openfga/model.fga}" \
      golang:1.26-bookworm \
      go run ./cmd/fga-setup
  )"
fi

OPENFGA_STORE_ID_VALUE="$(printf '%s\n' "${FGA_OUTPUT}" | awk -F= '/^OPENFGA_STORE_ID=/{print $2}' | tail -n1)"
OPENFGA_MODEL_ID_VALUE="$(printf '%s\n' "${FGA_OUTPUT}" | awk -F= '/^OPENFGA_MODEL_ID=/{print $2}' | tail -n1)"

[[ -n "${OPENFGA_STORE_ID_VALUE}" ]] || die "failed to extract OPENFGA_STORE_ID from setup output"
[[ -n "${OPENFGA_MODEL_ID_VALUE}" ]] || die "failed to extract OPENFGA_MODEL_ID from setup output"
log "verified configured Casdoor OIDC application ${CASDOOR_CLIENT_ID}"
log "bootstrapped OpenFGA store ${OPENFGA_STORE_ID_VALUE} with model ${OPENFGA_MODEL_ID_VALUE}"

runtime_env_tmp="$(mktemp)"
secret_env_tmp="$(mktemp)"
trap 'rm -f "${runtime_env_tmp}" "${secret_env_tmp}"' EXIT

cat >"${runtime_env_tmp}" <<EOF
# Generated by infra/ops/bootstrap-platform.sh (${MODE})
OPENFGA_STORE_ID=${OPENFGA_STORE_ID_VALUE}
OPENFGA_MODEL_ID=${OPENFGA_MODEL_ID_VALUE}
EOF

cat >"${secret_env_tmp}" <<EOF
# Generated secrets by infra/ops/bootstrap-platform.sh (${MODE})
EOF

install -m 600 "${runtime_env_tmp}" "${GENERATED_ENV_FILE}"
log "wrote derived runtime configuration to ${GENERATED_ENV_FILE}"

if [[ "${MODE}" == "prod" ]]; then
  [[ -n "${GENERATED_ENV_SECRET_REF:-}" ]] || die "GENERATED_ENV_SECRET_REF is required in production"
  [[ -n "${SECRET_BACKEND:-}" && "${SECRET_BACKEND}" != "none" && "${SECRET_BACKEND}" != "file" ]] || \
    die "production generated secrets must use a non-file secret backend"
  secret_backend_write_from_file "${GENERATED_ENV_SECRET_REF}" "${secret_env_tmp}"
  : > "${GENERATED_SECRET_ENV_FILE}"
  log "persisted generated secrets to remote secret backend ref ${GENERATED_ENV_SECRET_REF}"
else
  cat "${secret_env_tmp}" >> "${GENERATED_ENV_FILE}"
  : > "${GENERATED_SECRET_ENV_FILE}"
  log "in development mode appended generated secrets to ${GENERATED_ENV_FILE}"
fi
