#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"

usage() {
  cat <<'USAGE'
Usage: infra/ops/openfga-resource-access-smoke.sh

Runs a real OpenFGA resource-access smoke for Open Platform v1.1. The smoke
writes app -> resource_item read/write tuples, verifies check/list-objects,
revokes them, and verifies both checks become false.

Required env:
  OPENFGA_API_URL

Optional env:
  ENV_FILE                         defaults to .env
  SECRETS_ENV_FILE                 optional extra env file
  GENERATED_ENV_FILE               defaults to .env.generated
  OPENFGA_STORE_ID                 generated by OpenFGA bootstrap; must be nonempty for the smoke itself
  OPENFGA_MODEL_ID                 generated by OpenFGA bootstrap; must be nonempty for the smoke itself
  OPENFGA_RESOURCE_SMOKE_APP_ID
  OPENFGA_RESOURCE_SMOKE_RESOURCE_ID
  OPENFGA_RESOURCE_SMOKE_TIMEOUT   Go duration, defaults to 20s
  OPENFGA_RESOURCE_SMOKE_MODE      host or container; defaults to container in production, otherwise host when Go is available
  OPENFGA_RESOURCE_SMOKE_IMAGE     container-mode backend release image; defaults to BACKEND_IMAGE_REF
  OPENFGA_RESOURCE_SMOKE_EVIDENCE_FILE
USAGE
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

require_cmd jq

load_env

[[ -n "${OPENFGA_API_URL:-}" ]] || die "OPENFGA_API_URL is required"

reject_placeholder_if_set() {
  local key="$1"
  local value="${2:-}"
  shift 2 || true
  [[ -n "${value}" ]] || return 0
  local placeholder
  for placeholder in "$@"; do
    if [[ "${value}" == "${placeholder}" ]]; then
      die "${key} is using placeholder/default value (${placeholder}); set a real value first"
    fi
  done
}

reject_placeholder_if_set OPENFGA_STORE_ID "${OPENFGA_STORE_ID:-}" "REPLACE_WITH_OPENFGA_STORE_ID"
reject_placeholder_if_set OPENFGA_MODEL_ID "${OPENFGA_MODEL_ID:-}" "REPLACE_WITH_OPENFGA_MODEL_ID"

run_smoke_with_go() {
  (
    cd "${REPO_ROOT}/server"
    go run ./cmd/openfga-resource-smoke
  )
}

run_smoke_with_docker() {
  require_cmd docker
  local stack_name_value="${STACK_NAME:-${COMPOSE_PROJECT_NAME:-stuhelper}}"
  local docker_network_name="${DOCKER_NETWORK_NAME:-${stack_name_value}-backend}"
  local smoke_image_ref="${OPENFGA_RESOURCE_SMOKE_IMAGE:-${BACKEND_IMAGE_REF:-}}"
  [[ -n "${smoke_image_ref}" && "${smoke_image_ref}" != "REPLACE_WITH_BACKEND_IMAGE_REF" ]] ||
    die "BACKEND_IMAGE_REF or OPENFGA_RESOURCE_SMOKE_IMAGE is required in container mode"
  docker image inspect "${smoke_image_ref}" >/dev/null 2>&1 ||
    die "OpenFGA smoke release image is not present locally: ${smoke_image_ref}"

  docker run --rm --pull never \
    --read-only \
    --cap-drop ALL \
    --security-opt no-new-privileges \
    --tmpfs /app/tmp:rw,nosuid,nodev,noexec,size=16m,uid=1000,gid=1000 \
    --network "${docker_network_name}" \
    -e OPENFGA_API_URL="${OPENFGA_API_URL}" \
    -e OPENFGA_STORE_ID="${OPENFGA_STORE_ID}" \
    -e OPENFGA_MODEL_ID="${OPENFGA_MODEL_ID}" \
    -e OPENFGA_RESOURCE_SMOKE_APP_ID="${OPENFGA_RESOURCE_SMOKE_APP_ID:-}" \
    -e OPENFGA_RESOURCE_SMOKE_RESOURCE_ID="${OPENFGA_RESOURCE_SMOKE_RESOURCE_ID:-}" \
    -e OPENFGA_RESOURCE_SMOKE_TIMEOUT="${OPENFGA_RESOURCE_SMOKE_TIMEOUT:-}" \
    --entrypoint /app/openfga-resource-smoke \
    "${smoke_image_ref}"
}

smoke_mode() {
  if [[ -n "${OPENFGA_RESOURCE_SMOKE_MODE:-}" ]]; then
    printf '%s\n' "${OPENFGA_RESOURCE_SMOKE_MODE}"
    return
  fi
  if [[ "${APP_ENV:-}" == "production" ]]; then
    printf '%s\n' "container"
    return
  fi
  if command -v go >/dev/null 2>&1; then
    printf '%s\n' "host"
    return
  fi
  printf '%s\n' "container"
}

log "running Open Platform OpenFGA resource access smoke against ${OPENFGA_API_URL}" >&2
mode="$(smoke_mode)"
case "${mode}" in
  host)
    command -v go >/dev/null 2>&1 || die "Go is required when OPENFGA_RESOURCE_SMOKE_MODE=host"
    evidence_json="$(run_smoke_with_go)"
    ;;
  container)
    evidence_json="$(run_smoke_with_docker)"
    ;;
  *)
    die "OPENFGA_RESOURCE_SMOKE_MODE must be host or container"
    ;;
esac

if [[ -n "${OPENFGA_RESOURCE_SMOKE_EVIDENCE_FILE:-}" ]]; then
  mkdir -p "$(dirname "${OPENFGA_RESOURCE_SMOKE_EVIDENCE_FILE}")"
  printf '%s\n' "${evidence_json}" | jq . >"${OPENFGA_RESOURCE_SMOKE_EVIDENCE_FILE}"
fi

printf '%s\n' "${evidence_json}" | jq .
