CREATE TABLE public.authorization_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    role text NOT NULL,
    school_id bigint REFERENCES public.schools(id) ON DELETE RESTRICT,
    section_id text,
    desired_state text NOT NULL DEFAULT 'granted',
    projection_status text NOT NULL DEFAULT 'pending',
    revision bigint NOT NULL DEFAULT 1,
    reason text NOT NULL,
    created_by_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
    updated_by_user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
    activated_at timestamp with time zone,
    revoked_at timestamp with time zone,
    projected_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_authorization_grants_role
        CHECK (role IN (
            'super_admin',
            'school_admin',
            'section_admin',
            'section_moderator',
            'section_reviewer'
        )),
    CONSTRAINT chk_authorization_grants_desired_state
        CHECK (desired_state IN ('granted', 'revoked')),
    CONSTRAINT chk_authorization_grants_projection_status
        CHECK (projection_status IN ('pending', 'applied', 'failed')),
    CONSTRAINT chk_authorization_grants_revision
        CHECK (revision > 0),
    CONSTRAINT chk_authorization_grants_reason
        CHECK (
            char_length(reason) BETWEEN 1 AND 500
            AND reason = btrim(reason)
        ),
    CONSTRAINT chk_authorization_grants_scope
        CHECK (
            (
                role = 'super_admin'
                AND school_id IS NULL
                AND section_id IS NULL
            )
            OR (
                role = 'school_admin'
                AND school_id IS NOT NULL
                AND section_id IS NULL
            )
            OR (
                role IN ('section_admin', 'section_moderator', 'section_reviewer')
                AND school_id IS NOT NULL
                AND section_id = 'school_' || school_id::text || '_review_moderation'
            )
        )
);

CREATE UNIQUE INDEX authorization_grants_subject_role_scope_uidx
    ON public.authorization_grants (
        subject_user_id,
        role,
        school_id,
        section_id
    ) NULLS NOT DISTINCT;

CREATE INDEX authorization_grants_active_subject_idx
    ON public.authorization_grants (subject_user_id, role, school_id, section_id)
    WHERE desired_state = 'granted' AND projection_status = 'applied';

CREATE INDEX authorization_grants_projection_idx
    ON public.authorization_grants (projection_status, desired_state, updated_at, id);
