-- One-way reset requested by the product owner: legacy student-verification
-- facts are not migrated, backed up, shadow-read, or retained as compatibility
-- evidence. User accounts, QQ bindings, phone state, admission policy and
-- general business data are deliberately outside this purge.

-- Drain every in-flight writer before collecting object keys or deleting
-- evidence. These locks are intentionally broad and one-shot: without them an
-- old application transaction could commit a profile, credential or release
-- action after the corresponding DELETE/UPDATE had already run.
LOCK TABLE
    public.user_profiles,
    public.user_identities,
    public.user_verification_credentials,
    public.freshman_camera_handoffs,
    public.freshman_verification_materials,
    public.freshman_verification_applications,
    public.student_email_inbound_events,
    public.student_email_inbound_challenges,
    public.student_manual_review_events,
    public.student_manual_camera_handoffs,
    public.student_manual_review_materials,
    public.student_manual_review_cases,
    public.student_verification_attempts,
    public.student_verification_applications,
    public.student_subject_conflicts,
    public.student_enrollment_subjects,
    public.student_verification_event_outbox,
    public.student_eligibility_revisions,
    public.school_verification_suggestions,
    public.domain_event_outbox,
    public.admission_bot_action_outbox,
    public.group_admission_sessions,
    academic.student_roster_active,
    academic.student_roster_snapshots,
    academic.buaa_students
IN ACCESS EXCLUSIVE MODE;

CREATE TABLE public.student_verification_object_purge_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key text NOT NULL UNIQUE,
    source_kind text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0,
    available_at timestamp with time zone NOT NULL DEFAULT NOW(),
    claimed_at timestamp with time zone,
    claim_owner character varying(36),
    last_error_code text,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_student_verification_object_purge_source
        CHECK (source_kind IN ('legacy_identity_photo', 'legacy_freshman_material', 'student_manual_material')),
    CONSTRAINT chk_student_verification_object_purge_status
        CHECK (status IN ('pending', 'claimed', 'dead_letter')),
    CONSTRAINT chk_student_verification_object_purge_attempts
        CHECK (attempts >= 0),
    CONSTRAINT chk_student_verification_object_purge_claim
        CHECK (
            (status = 'claimed' AND claimed_at IS NOT NULL AND claim_owner IS NOT NULL)
            OR (status <> 'claimed' AND claimed_at IS NULL AND claim_owner IS NULL)
        ),
    CONSTRAINT chk_student_verification_object_purge_owner
        CHECK (
            claim_owner IS NULL
            OR claim_owner ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        )
);

CREATE INDEX student_verification_object_purge_pending_idx
    ON public.student_verification_object_purge_queue (available_at, id)
    WHERE status IN ('pending', 'claimed');

COMMENT ON TABLE public.student_verification_object_purge_queue IS
    'Transient deletion queue only. A row is physically removed immediately after its private object is deleted; it is not a backup or audit archive';

INSERT INTO public.student_verification_object_purge_queue (object_key, source_kind)
SELECT DISTINCT object_key, source_kind
FROM (
    SELECT NULLIF(btrim(doc_photo_front), '') AS object_key, 'legacy_identity_photo'::text AS source_kind
    FROM public.user_identities
    UNION ALL
    SELECT NULLIF(btrim(doc_photo_back), ''), 'legacy_identity_photo'::text
    FROM public.user_identities
    UNION ALL
    SELECT NULLIF(btrim(doc_photo_selfie), ''), 'legacy_identity_photo'::text
    FROM public.user_identities
    UNION ALL
    SELECT NULLIF(btrim(object_key), ''), 'legacy_freshman_material'::text
    FROM public.freshman_verification_materials
    UNION ALL
    SELECT NULLIF(btrim(object_key), ''), 'student_manual_material'::text
    FROM public.student_manual_review_materials
) objects
WHERE object_key IS NOT NULL
ON CONFLICT (object_key) DO NOTHING;

CREATE TEMP TABLE legacy_student_verification_users (
    user_id bigint PRIMARY KEY
) ON COMMIT DROP;

INSERT INTO legacy_student_verification_users (user_id)
SELECT user_id FROM public.user_profiles
UNION
SELECT user_id FROM public.user_identities
UNION
SELECT user_id FROM public.user_verification_credentials
UNION
SELECT user_id FROM public.freshman_verification_applications
UNION
SELECT user_id FROM public.student_verification_applications
ON CONFLICT (user_id) DO NOTHING;

-- Replace any pending positive profile projection with a negative projection.
-- The worker resolves the new student-verification authority directly, so the
-- legacy profile row can be deleted completely.
INSERT INTO public.domain_event_outbox (
    stream, job_type, dedupe_key, payload, status, attempt_count,
    available_at, locked_at, last_error, created_at, updated_at
)
SELECT
    'iam_openfga_tuple_sync',
    'user_profile_projection',
    'user-profile-projection:' || user_id,
    jsonb_build_object('userID', user_id, 'approved', false),
    'pending',
    0,
    NOW(),
    NULL,
    NULL,
    NOW(),
    NOW()
FROM legacy_student_verification_users
ON CONFLICT (stream, dedupe_key)
DO UPDATE SET
    job_type = EXCLUDED.job_type,
    payload = EXCLUDED.payload,
    status = 'pending',
    attempt_count = 0,
    available_at = NOW(),
    locked_at = NULL,
    last_error = NULL,
    updated_at = NOW();

-- Old admission projection jobs may otherwise recreate a credential from a
-- profile after the purge. Target admission now evaluates the new credential
-- domain directly and never consumes these jobs.
DELETE FROM public.domain_event_outbox
WHERE job_type IN ('admission_verification_projection', 'verified_student_role')
   OR stream = 'iam_casdoor_role_sync';

-- Stop every not-yet-executed release derived from the deleted evidence and
-- return in-flight sessions to an explicit requirements state. Historical
-- admitted/released sessions are retained as admission audit, not identity proof.
UPDATE public.admission_bot_action_outbox
SET status = 'stale',
    last_error = NULL,
    updated_at = NOW()
WHERE action = 'release'
  AND status IN ('pending', 'failed', 'dispatched', 'dead_letter');

UPDATE public.group_admission_sessions
SET status = 'awaiting_requirements',
    eligibility_revision = NULL,
    eligibility_evaluated_at = NULL,
    requirements_status = 'awaiting_requirements',
    verified_at = NULL,
    manual_review_deadline_at = NULL,
    updated_at = NOW()
WHERE status IN ('eligible', 'action_pending', 'pending_manual_review');

-- Delete target and legacy credentials first because enrollment subjects and
-- old freshman applications are referenced by them.
DELETE FROM public.user_verification_credentials;
DELETE FROM public.student_verification_event_outbox;
DELETE FROM public.student_eligibility_revisions;
DELETE FROM public.student_subject_conflicts;
DELETE FROM public.student_enrollment_subjects;

-- Pre-release target workflow rows are data, not schema/configuration. Remove
-- them explicitly instead of relying on cascades so the purge scope remains
-- reviewable and zero-row verification can name every target table.
DELETE FROM public.student_email_inbound_events;
DELETE FROM public.student_email_inbound_challenges;
DELETE FROM public.student_manual_review_events;
DELETE FROM public.student_manual_camera_handoffs;
DELETE FROM public.student_manual_review_materials;
DELETE FROM public.student_manual_review_cases;
DELETE FROM public.student_verification_attempts;
DELETE FROM public.student_verification_applications;
DELETE FROM public.school_verification_suggestions;

-- Old admission-coupled material review is not a compatibility source.
DELETE FROM public.freshman_camera_handoffs;
DELETE FROM public.freshman_verification_materials;
DELETE FROM public.freshman_verification_applications;

-- Old identity rows include names, encrypted document numbers and material
-- object references. Objects were queued above; the database rows are removed
-- in the same migration.
DELETE FROM public.user_identities;

-- No neutral shell, migration marker, or compatibility row is retained.
DELETE FROM public.user_profiles;

-- Both the legacy upsert roster and any pre-release target snapshot are
-- discarded. A newly validated full snapshot must be activated before roster-
-- dependent methods can become available.
DELETE FROM academic.student_roster_active;
DELETE FROM academic.student_roster_snapshots;
TRUNCATE TABLE academic.buaa_students;

-- Remove user-visible artifacts and audit payloads from the retired flows.
DELETE FROM public.notifications
WHERE type IN (
    'identity_approved', 'identity_rejected',
    'student_approved', 'student_rejected',
    'freshman_approved', 'freshman_rejected', 'freshman_near_expiry'
);

DELETE FROM public.audit_events
WHERE resource_type IN (
    'identity_review',
    'identity_review_material',
    'student_verification_review',
    'student_verification',
    'student_verification_application',
    'student_verification_credential',
    'freshman_verification',
    'freshman_verification_application',
    'freshman_verification_material'
)
   OR event_type LIKE 'student_verification.%'
   OR event_type LIKE 'student_credential.%'
   OR event_type LIKE 'freshman_verification.%';

-- Keep a still-running old binary from recreating deleted facts while the new
-- release replaces it. The target student-verification service never writes
-- the retired tables, and every target credential is tied to a target
-- verification application. This database fence is intentionally permanent;
-- application rollback may not re-enable legacy writers.
CREATE FUNCTION public.reject_retired_student_verification_write()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'retired student-verification write path is permanently disabled'
        USING ERRCODE = '55000';
END
$$;

CREATE TRIGGER reject_user_profiles_legacy_write
BEFORE INSERT OR UPDATE ON public.user_profiles
FOR EACH ROW EXECUTE FUNCTION public.reject_retired_student_verification_write();

CREATE TRIGGER reject_user_identities_legacy_write
BEFORE INSERT OR UPDATE ON public.user_identities
FOR EACH ROW EXECUTE FUNCTION public.reject_retired_student_verification_write();

CREATE TRIGGER reject_freshman_applications_legacy_write
BEFORE INSERT OR UPDATE ON public.freshman_verification_applications
FOR EACH ROW EXECUTE FUNCTION public.reject_retired_student_verification_write();

CREATE TRIGGER reject_freshman_materials_legacy_write
BEFORE INSERT OR UPDATE ON public.freshman_verification_materials
FOR EACH ROW EXECUTE FUNCTION public.reject_retired_student_verification_write();

CREATE TRIGGER reject_freshman_handoffs_legacy_write
BEFORE INSERT OR UPDATE ON public.freshman_camera_handoffs
FOR EACH ROW EXECUTE FUNCTION public.reject_retired_student_verification_write();

CREATE TRIGGER reject_buaa_upsert_roster_legacy_write
BEFORE INSERT OR UPDATE ON academic.buaa_students
FOR EACH ROW EXECUTE FUNCTION public.reject_retired_student_verification_write();

CREATE TRIGGER reject_unscoped_student_credential_legacy_write
BEFORE INSERT OR UPDATE ON public.user_verification_credentials
FOR EACH ROW
WHEN (NEW.verification_application_id IS NULL)
EXECUTE FUNCTION public.reject_retired_student_verification_write();
