securitySchemes:
  cookieAuth:
    type: apiKey
    in: cookie
    name: access_token
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
  serviceTokenAuth:
    type: http
    scheme: bearer
    bearerFormat: opaque
